### ISSUE TITLE
Implement utilities for V-COCO

### ISSUE THREAD

**Issue by fredzzhang** [fredzzhang/upt#11]

**Comment by leijue222** [comment]
Looking forward to adding support for vcoco evaluation.
https://github.com/fredzzhang/upt/blob/192743045e4c5f6827299fdc15809f5b97ac1b8e/main.py#L96-L99

**Comment by leijue222** [comment]
Hi, @fredzzhang .
I found cache.pkl to eval vcoco is too slow, it need spend 30mins( I think it is the [v-coco](https://github.com/s-gupta/v-coco) repository code problem ).
Do you have any suggestions to speed up it?
