### ISSUE TITLE
single video inference code?

### ISSUE THREAD

**Issue by dragen1860** [fredzzhang/upt#28]
Dear author:
   Thanks for sharing the insightful work. it looks great. Before diving deeply into your work, a lot of researcher like me, would like to firstly play with your models. I think a easy to use inference video py scripts would make it much efficient to know your work. Thank you.

**Comment by fredzzhang** [comment]
Hi @dragen1860,

Thanks for the suggestion. We will consider adding it in the future.

Fred.
