### ISSUE TITLE
self.coop_layer or self.comp_layer

### ISSUE THREAD

**Issue by chenminupup** [fredzzhang/upt#39]
Hello, may I ask why all the three indicators on Hicodet are 0.0000 after removing this layer？

**Comment by fredzzhang** [comment]
Hi @chenminupup,

I'm not sure what you mean. Are you referring to the mAP of the model? And what did you remove exactly, both layers or one of them?

Fred.

**Comment by chenminupup** [comment]
yes， I mean the mAP of the model is 0.0000 when I remove one or both of them。

The mAP is 0.0000, rare: 0.0000, none-rare: 0.0000

unary_tokens, unary_attn = self.coop_layer(unary_tokens, box_pair_spatial_reshaped)  

pairwise_tokens, pairwise_attn = self.comp_layer(pairwise_tokens)

**Comment by fredzzhang** [comment]
Are you able to reproduce the results while keeping both layers?

**Comment by chenminupup** [comment]
yes，the results didn't differ much

**Comment by fredzzhang** [comment]
Hi @chenminupup,

I just repeated the experiment and got `full: 0.2370, rare: 0.1701, none-rare: 0.2569` for `UPT-R50` with both layers removed. I think you might have used an incorrect path to the checkpoint, in which case a randomly initialised model will be used, hence the zero mAP. Can you check if you've got the path correct?

Fred.

**Comment by chenminupup** [comment]
Hi， I have the correct file loading path, but the result is still 0.0000

=> Rank 0: continue from saved checkpoint /mnt/hdd1/cm/ckpt_upt/upt-r50-hicodet-no2att/ckpt_94080_20.pt
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9546/9546 [11:24<00:00, 13.94it/s]
WARNING: Collected results are empty. Return zero AP for class 0.
WARNING: Collected results are empty. Return zero AP for class 1.
...
WARNING: Collected results are empty. Return zero AP for class 598.
WARNING: Collected results are empty. Return zero AP for class 599.
The mAP is 0.0000, rare: 0.0000, none-rare: 0.0000

**Comment by fredzzhang** [comment]
Based on the log, the network is returning empty results for each image. Can you attach the exact changes you made to remove the two layers?
