### ISSUE TITLE
Predicted object class instead of just number?

### ISSUE THREAD

**Issue by xiaoxiaoczw** [fredzzhang/upt#40]
Hi,

thanks for the amazing work! I would like to ask where can we see the predicted object class of each bounding box, or the prediction result for a triplet form? Thank you!

**Comment by xiaoxiaoczw** [comment]
> Hi,
> 
> thanks for the amazing work! I would like to ask where can we see the predicted object class on each image, or the prediction result for a triplet form? Thank you!

**Comment by fredzzhang** [comment]
Hi @xiaoxiaoczw,

Thanks for taking an interest in our work. You can find the detailed inference instructions [here](https://github.com/fredzzhang/upt#inference). To answer your question, if you do not use the flag `--action` to specify action index, the script will automatically print out a list of predictions in the terminal, including the object class and HOI class.

Fred.

**Comment by xiaoxiaoczw** [comment]
Hi @fredzzhang ,

Thank you for your reply! When I ran inference.py, I got the output as follows. Only the bounding box and their number printed on image, and the predicted action, pair numbers and their score printed on terminal. Through these, I can't get the exact name of each detected object class. Maybe what else did I ignore? Thank you!

**Comment by fredzzhang** [comment]
Hmm...you are correct. I guess I forgot to add the object names as part of the output. I have fixed that in PR #41. You should be able to see object names now after `git pull`.

**Comment by xiaoxiaoczw** [comment]
Perfect!

**Comment by xiaoxiaoczw** [comment]
Additional small question, why do you use a different order than the object-list provided by HICO-DET?

**Comment by fredzzhang** [comment]
It's the MS COCO object list used here, since it's more prevalent. The HICO-DET object list is rather inconvenient in that regard.

**Comment by xiaoxiaoczw** [comment]
Ah, thank you!
