### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by SherlockHolmes221** [fredzzhang/upt#46]
ModuleNotFoundError: No module named 'pocket.data'; 'pocket' is not a package
I have installed pocket using pip3 install pocket

**Comment by fredzzhang** [comment]
Hi @SherlockHolmes221,

`pocket` is not a published package. Please follow the installation instructions [here](https://github.com/fredzzhang/pocket)

Fred.

**Comment by SherlockHolmes221** [comment]
Thx

**Comment by leijue222** [comment]
I followed this [step ](https://github.com/fredzzhang/pocket#installation) and run `mnist.py `successful. But under UPT, I still failed with pocket environment.
```
(pocket) ming-t@mingt-Z490-UD:UPT/pocket$ conda develop pocket
added /media/ming-t/Deng/relation_mppe/HOI-UPT/pocket-lib/pocket
completed operation for: /media/ming-t/Deng/relation_mppe/HOI-UPT/pocket-lib/pocket

(pocket) ming-t@mingt-Z490-UD:UPT/pocket$ python inference.py --resume checkpoints/upt-r50-vcoco.pt --image-path ./assets/umbrella.jpeg --action 0 --dataset vcoco
Traceback (most recent call last):
  File "inference.py", line 12, in <module>
    import pocket
ModuleNotFoundError: No module named 'pocket'
```

**Comment by fredzzhang** [comment]
Hi @leijue222,

Can you print out the system paths in Python and attach the results?

```python
import sys
print(sys.path)
```

**Comment by leijue222** [comment]
`['', '/home/ming-t/anaconda3/envs/pocket/lib/python38.zip', '/home/ming-t/anaconda3/envs/pocket/lib/python3.8', '/home/ming-t/anaconda3/envs/pocket/lib/python3.8/lib-dynload', '/home/ming-t/anaconda3/envs/pocket/lib/python3.8/site-packages', '/media/ming-t/Deng/relation_mppe/HOI-UPT/pocket-lib/pocket', '/media/ming-t/Deng/relation_mppe/HOI-UPT/pocket']`

![image](https://user-images.githubusercontent.com/30276789/193737616-40b2d781-84f4-4060-acc8-e92e31f211b3.png)

Thanks, I solved the environment problem by moving the pocket directory to the root directory

**Comment by fredzzhang** [comment]
Ok, that's good to hear. You seem to have added multiple copies of the `pocket` library to the system path. That might have caused some confusion.
```
'/media/ming-t/Deng/relation_mppe/HOI-UPT/pocket-lib/pocket'
'/media/ming-t/Deng/relation_mppe/HOI-UPT/pocket'
```

In general, it's probably better to keep `pocket` in a different position other than where your projects are, just as you did in the end.

**Comment by leijue222** [comment]
> In general, it's probably better to keep pocket in a different position other than where your projects are

If I put pocket under UPT(where my projects are), I can run `inference,py` successful.
![image](https://user-images.githubusercontent.com/30276789/193765602-59f37194-13b9-4edb-998d-b152e9381cd5.png)

On the contrary, if I keep pocket in a different position, the pocker still report error.
![image](https://user-images.githubusercontent.com/30276789/193766635-c3cfb476-e734-4747-a419-082298858672.png)

It seems that conda develop pocket has no effect after adding the path.
Is there any error in my operation? How to solve it?

**Comment by leijue222** [comment]
In addition, I tried to evaluate the results of vcoco.

I use `python main.py --cache --dataset vcoco --data-root vcoco/ --partitions trainval test --output-dir vcoco-r50 --resume /path/to/model` generate a pkl file.
Then I use this code to eval
```
from vsrl_eval import VCOCOeval
vsrl_annot_file = 'data/vcoco/vcoco_val.json'
coco_file = 'data/instances_vcoco_all_2014.json'
split_file = 'data/splits/vcoco_val.ids'

vcocoeval = VCOCOeval(vsrl_annot_file, coco_file, split_file)

det_file = '/media/ming-t/Deng/relation_mppe/HOI-UPT/vcoco-r50/cache.pkl'
vcocoeval._do_eval(det_file, ovr_thresh=0.5)
```
 but it will report  a error, which seems to be caused by environmental problems.
```
loading annotations into memory...
Done (t=1.98s)
creating index...
index created!
loading vcoco annotations...
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    vcocoeval._do_eval(det_file, ovr_thresh=0.5)
  File "/media/ming-t/Deng/relation_mppe/lib/vcoco/vsrl_eval.py", line 192, in _do_eval
    self._do_agent_eval(vcocodb, detections_file, ovr_thresh=ovr_thresh)
  File "/media/ming-t/Deng/relation_mppe/lib/vcoco/vsrl_eval.py", line 332, in _do_agent_eval
    dets = pickle.load(f)
  File "/media/ming-t/Deng/relation_mppe/lib/pocket/utils/__init__.py", line 2, in <module>
    from .meters import *
  File "/media/ming-t/Deng/relation_mppe/lib/pocket/utils/meters.py", line 17, in <module>
    from ..ops import to_tensor
ValueError: attempted relative import beyond top-level package
```
