### ISSUE TITLE
How I can eval model after each epoch end?

### ISSUE THREAD

**Issue by SherlockHolmes221** [fredzzhang/upt#47]
How I can eval model after each epoch end? Thanks

**Comment by fredzzhang** [comment]
Hi @SherlockHolmes221,

The evaluation code is implemented for a single GPU, without distributed data parallel. So, it wasn't included during training. However, all checkpoints after each epoch will be cached by default in the directory you specified. Each checkpoint is named as `ckpt_steps_epochs`. You can run evaluation on the checkpoints you are interested in.

Fred.

**Comment by SherlockHolmes221** [comment]
Thx
