### ISSUE TITLE
About the evaluation code for HICO-DET

### ISSUE THREAD

**Issue by ghost** [fredzzhang/upt#54]
Thanks for your work. 

Does the current evaluation code only support default settings on HICO-DET?

It seems that there are no hyperparameters about Default Setting and Known Objects Setting in main.py. 

Thanks!

**Comment by fredzzhang** [comment]
Hi @Anon-account,

If you want results in the known object setting, you will have to cache the results in Matlab format. If you go to [launch_template.sh](https://github.com/fredzzhang/upt/blob/main/launch_template.sh), you can find the corresponding commands to cache results for Matlab evaluation.

Fred.
