### ISSUE TITLE
code bug?

### ISSUE THREAD

**Issue by ltttpku** [fredzzhang/upt#57]
Thanks for your amazing work.

i'm confused about the code here: [https://github.com/fredzzhang/upt/blob/192743045e4c5f6827299fdc15809f5b97ac1b8e/interaction_head.py#L333](url)

the code `x_keep, y_keep = torch.nonzero(torch.logical_and(x != y, x < n_h)).unbind(1)` is designed for getting valid human-object pairs, but i think it also causes some human-human pairs without the constraint `y >= n_h`.

**Comment by fredzzhang** [comment]
Hi @ltttpku,

It depends on the dataset. For HICO-DET and V-COCO, which the model was developed on, human-human interactions are not considered.

Fred.

**Comment by ltttpku** [comment]
hmm i know, i mean it seems that your code can generate some human-human pairs, which is unexpected.

**Comment by fredzzhang** [comment]
Oh, sorry I made a mistake. For HICO-DET dataset, there are in fact human-human interactions. The constraint you mentioned above removes object-object pairs, which are not considered.

Fred.

**Comment by ltttpku** [comment]
HICO-DET dataset doesn't contain human-human interactions according to their officially provided "list of HOIs" here [http://www-personal.umich.edu/~ywchao/hico/](url).

What did i miss?

**Comment by fredzzhang** [comment]
You can find the list of interactions [here](https://drive.google.com/file/d/1ipvRTUF2zpOlHHqzbEb29iwscizoM1CK/view). In particular, interactions 161-170 are human-human interactions (e.g. person carrying person, person greeting person).

**Comment by ltttpku** [comment]
ohh, i see. Thanks for your patience!
