### ISSUE TITLE
A question about v-coco dataset

### ISSUE THREAD

**Issue by ltttpku** [fredzzhang/upt#65]
Hi, thank you for your code; But i have a question about the V-COCO dataset you implemented.

V-COCO is a subset of COCO dataset and has 10, 396 images (`5,400 for training` and `4,964 for testing`) as stated in paper.
However, when executing your code for v-coco dataset, I found` len(trainset)==4969 `and `len(testset)==4532`. The reported number of training images does not match the actual one.

**Comment by fredzzhang** [comment]
Hi @ltttpku,

If I remember this correctly, there are images without sufficient bounding box annotations. So I removed those images. It's the same situation with HICO-DET as well. The authors claimed there are `38118` training images, while in fact only `37633` of those images have bounding box annotations.

Fred.

**Comment by ltttpku** [comment]
ohh, I see. Thanks!
