### ISSUE TITLE
Detection results, mAP calculation

### ISSUE THREAD

**Issue by hutuo1213** [fredzzhang/upt#66]
Hi @fredzzhang ,

Suppose you detect an image with a total of 15 pairs of Human-Object interacting with a total of 114 valid verbs. Even if all predictions are correct, a large number of predicted triples will be treated as negative samples, does this affect mAP? (QPIC's prediction is only 100) 

If 114 pieces of information are considered the final detection result, then there is no way to know exactly what kind of interaction it is, and it seems that you need to specify all actions, like the visualization of actions in your reasoning.

The above is the confusion that arises when I check the code, I hope you can give me some guidance.

yaoyaosanqi.

**Comment by fredzzhang** [comment]
Hi @yaoyaosanqi,

In UPT, we sample up to `15` humans and `15` objects in each image, which amounts to at most `(15-1) * 15 = 210` pairs. That should be sufficient for majority of the images. Although there might be some niche images with a particularly large number of positive pairs, it's rare enough to just ignore.

> If 114 pieces of information are considered the final detection result, then there is no way to know exactly what kind of interaction it is, and it seems that you need to specify all actions, like the visualization of actions in your reasoning.

The network produces results for all potential interactions in one go. The option to specify actions is only implemented to make the visualisations a bit neater. If you want all the results, just remove the `--action` flag. All results will then be printed.

Fred.

**Comment by hutuo1213** [comment]
Thank you from the bottom of my heart!
