### ISSUE TITLE
torch.multiprocessing.spawn.ProcessRaisedException

### ISSUE THREAD

**Issue by hutuo1213** [fredzzhang/upt#68]
Hi, @fredzzhang ：

I had a sudden situation, before I kept the same settings, it ran without problems. Do you know how?

`nohup: ignoring input
Namespace(alpha=0.5, aux_loss=True, backbone='resnet50', batch_size=8, bbox_loss_coef=5, box_score_thresh=0.2, cache=False, clip_max_norm=0.1, data_root='./hicodet', dataset='hicodet', dec_layers=6, device='cuda', dilation=False, dim_feedforward=2048, dropout=0.1, enc_layers=6, eos_coef=0.1, epochs=30, eval=False, fg_iou_thresh=0.5, gamma=0.2, giou_loss_coef=2, hidden_dim=256, lr_drop=10, lr_head=0.0001, max_instances=15, min_instances=3, nheads=8, num_queries=100, num_workers=2, output_dir='checkpoints/upt-r50-hicodet2244', partitions=['train2015', 'test2015'], port='3714', position_embedding='sine', pre_norm=False, pretrained='checkpoints/detr-r50-hicodet.pth', print_interval=500, repr_dim=512, resume='', sanity=False, seed=66, set_cost_bbox=5, set_cost_class=1, set_cost_giou=2, weight_decay=0.0001, world_size=2)
Load weights for the object detector from checkpoints/detr-r50-hicodet.pth
=> Rank 0: start from a randomly initialised model
=> Rank 1: start from a randomly initialised model
Traceback (most recent call last):
  File "main.py", line 220, in <module>
    mp.spawn(main, nprocs=args.world_size, args=(args,))
  File "/home1/quan107552101247/.conda/envs/pocket/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home1/quan107552101247/.conda/envs/pocket/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home1/quan107552101247/.conda/envs/pocket/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: `

`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home1/quan107552101247/.conda/envs/pocket/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home1/quan107552101247/upt/main.py", line 137, in main
    engine(args.epochs)
  File "/home1/quan107552101247/spatially-conditioned-graphs/pocket/pocket/core/distributed.py", line 139, in __call__
    self._on_each_iteration()
  File "/home1/quan107552101247/upt/utils.py", line 139, in _on_each_iteration
    if loss_dict['interaction_loss'].isnan():
TypeError: list indices must be integers or slices, not str`

yaoyaosanqi.

**Comment by fredzzhang** [comment]
Hi @yaoyaosanqi,

The model returns a `dict` containing the losses during training, while during test it returns a `list` of detections. The error `loss_dict['interaction_loss'].isnan(): TypeError: list indices must be integers or slices, not str` suggests a `list` has been returned during training.

I need to know what changes you made to the code to find the problem. Run `git status` to find scripts that have been modified and look into the changes.

Fred.

**Comment by hutuo1213** [comment]
Following your suggestion, I checked the code and found that I commented out the training part when I was debugging before.

The issue was caused by my negligence. Already solved, thank you very much!

`        #if self.training:##$$targets:4list,只经过数据预处理,一个list一张图片
         # interaction_loss = self.compute_interaction_loss(boxes, bh, bo, logits, prior, targets)
         # loss_dict = dict(
         #     interaction_loss=interaction_loss
         # )
         # return loss_dict`
