### ISSUE TITLE
Detected human–object interactions on video

### ISSUE THREAD

**Issue by rouge012** [fredzzhang/upt#75]
Hi! How could I detect human–object interactions on video like your demo on data in the wild?

Thank you!

**Comment by fredzzhang** [comment]
Hi @rouge012,

I didn't put together a script that generates the `.gif` demo directly. To get something similar to that, you could just extract the frames from your videos and run inference on each one of them. The `inference.py` script would be a good starting point. It should be fairly easy to modify. After you get the visualistaions for each frame, there are softwares that can stitch them into a `.gif` file.

Hope that answers your question.

Fred.
