### ISSUE TITLE
VCOCO Scenario 1 and Scenario 2

### ISSUE THREAD

**Issue by hutuo1213** [fredzzhang/upt#76]
Hi, @fredzzhang

I found that there are evaluation strategies for scenario 1 and scenario 2 in VCOCO. I checked the vcoco's annotations file: 
#{"boxes_h": [], "boxes_o": [], "actions": [], "objects": [], "file_name": "COCO_train2014_000000565694.jpg"}

Because UPT must detect human-object pairs. I would like to know how vcoco generates scenario 1 and scenario 2 results under supervised training. Can you indicate where the relevant code is?

Thank you so much!
yaoyaosanqi.

**Comment by fredzzhang** [comment]
Hi @yaoyaosanqi,

Apologies for the late reply. You can find the code used to cache results [here](https://github.com/fredzzhang/upt/blob/main/utils.py#L286).

Fred,

**Comment by yaoyaosanqi** [comment]
Hi,

Based on your tips, I solved the above problem. 
I would like to know how the UPT predicts scenario 1 and scenario 2, which needs to be predicted as [0,0,0,0] for occlusion objects. Scenario 2 needs to ignore object prediction. Does UPT have the function to predict [0,0,0,0] of the occluded object?

Thank you so much!
yaoyaosanqi.
