### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'lr_backbone'

### ISSUE THREAD

**Issue by Dawn-LX** [fredzzhang/upt#77]
hello,
when I run `python main.py --eval --backbone resnet101 --dilation --resume /path/to/model`

It raise `AttributeError: 'Namespace' object has no attribute 'lr_backbone'`

It seems that the `args` used to build_dert is not covered by the `args` in main.py

Can you provide some instructions about how to combine these two (build detr and run upt) ?

details:
```
(torch111) gaokaifeng@server1:~/project/upt$ python main.py --eval --backbone resnet101 --dilation --resume /path/to/model
Namespace(alpha=0.5, aux_loss=True, backbone='resnet101', batch_size=2, bbox_loss_coef=5, box_score_thresh=0.2, cache=False, clip_max_norm=0.1, data_root='./hicodet', dataset='hicodet', dec_layers=6, device='cuda', dilation=True, dim_feedforward=2048, dropout=0.1, enc_layers=6, eos_coef=0.1, epochs=20, eval=True, fg_iou_thresh=0.5, gamma=0.2, giou_loss_coef=2, hidden_dim=256, lr_drop=10, lr_head=0.0001, max_instances=15, min_instances=3, nheads=8, num_queries=100, num_workers=2, output_dir='checkpoints', partitions=['train2015', 'test2015'], port='1234', position_embedding='sine', pre_norm=False, pretrained='', print_interval=500, repr_dim=512, resume='/path/to/model', sanity=False, seed=66, set_cost_bbox=5, set_cost_class=1, set_cost_giou=2, weight_decay=0.0001, world_size=1)
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    mp.spawn(main, nprocs=args.world_size, args=(args,))
  File "/home/gaokaifeng/anaconda3/envs/torch111/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/gaokaifeng/anaconda3/envs/torch111/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/gaokaifeng/anaconda3/envs/torch111/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/gaokaifeng/anaconda3/envs/torch111/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/gaokaifeng/project/upt/main.py", line 71, in main
    upt = build_detector(args, object_to_target)
  File "/home/gaokaifeng/project/upt/upt.py", line 268, in build_detector
    detr, _, postprocessors = build_model(args)
  File "/home/gaokaifeng/project/upt/detr/models/__init__.py", line 6, in build_model
    return build(args)
  File "/home/gaokaifeng/project/upt/detr/models/detr.py", line 320, in build
    backbone = build_backbone(args)
  File "/home/gaokaifeng/project/upt/detr/models/backbone.py", line 114, in build_backbone
    train_backbone = args.lr_backbone > 0
AttributeError: 'Namespace' object has no attribute 'lr_backbone'
```

**Comment by Dawn-LX** [comment]
https://github.com/fredzzhang/upt/blob/192743045e4c5f6827299fdc15809f5b97ac1b8e/upt.py#L268

here the `build_model` function directly use the `args` from UPT to build DETR, but they not the same.

I wonder that whether it is because I was not run the UPT in a correct manner ?

**Comment by fredzzhang** [comment]
Hi @Dawn-LX,

I think you are on the wrong head for the submodule. The corresponding line that resulted in the error was commented out. Make sure the submodule `detr` is on head `820d17a`. A simple way to check is to run `git status`. If you see modifications in the submodules, make sure to remove them.

Fred.

**Comment by Dawn-LX** [comment]
> Hi @Dawn-LX,
> 
> I think you are on the wrong head for the submodule. The corresponding line that resulted in the error was commented out. Make sure the submodule `detr` is on head `820d17a`. A simple way to check is to run `git status`. If you see modifications in the submodules, make sure to remove them.
> 
> Fred.

Thank you for your reply!

But my `detr` submodule was downloaded by directly using `git` to clone the url that provided in the .gitmudules here:
https://github.com/fredzzhang/upt/blob/192743045e4c5f6827299fdc15809f5b97ac1b8e/.gitmodules#L11


and based on the above, my hash id is :
```
(base) gaokaifeng@server1:~/project/upt/detr$ git rev-parse main
7a4ff09adf5ca9c1790f4f82829bebecad38e41b
```

**Comment by Dawn-LX** [comment]
> > Hi @Dawn-LX,
> > I think you are on the wrong head for the submodule. The corresponding line that resulted in the error was commented out. Make sure the submodule `detr` is on head `820d17a`. A simple way to check is to run `git status`. If you see modifications in the submodules, make sure to remove them.
> > Fred.
> 
> Thank you for your reply!
> 
> But my `detr` submodule was downloaded by directly using git clone the url that provided in the .gitmudules here:
> 
> https://github.com/fredzzhang/upt/blob/192743045e4c5f6827299fdc15809f5b97ac1b8e/.gitmodules#L11
> 
> and based on the above, my hash id is :
> 
> ```
> (base) gaokaifeng@server1:~/project/upt/detr$ git rev-parse main
> 7a4ff09adf5ca9c1790f4f82829bebecad38e41b
> ```

Now I get it. I should directly click the folder [`detr @ 820d17a`](https://github.com/fredzzhang/detr/tree/820d17abc697e8dd5f49d4cd1fdbde412545bac5) and link to the correct head `820d17abc697e8dd5f49d4cd1fdbde412545bac5`

So perhaps it would be helpful for future researchers if you could kindly update the url in the `.gitmodules` file to avoid similar issues in the future.

**Comment by Dawn-LX** [comment]
Another problem:

Now in the page of https://github.com/fredzzhang/detr/tree/820d17abc697e8dd5f49d4cd1fdbde412545bac5

when I clone this by
![image](https://user-images.githubusercontent.com/48169011/230761308-389f13d0-a806-47f0-9771-5b264c4ec883.png)

the cloned detr repo is still at the head: `7a4ff09adf5ca9c1790f4f82829bebecad38e41b`

The only way I can get into head `820d17a` is downloading it as 
 `detr-820d17abc697e8dd5f49d4cd1fdbde412545bac5.zip` and rename it as `detr`. 

Is there a more convenient (and more formal) way to achieve head `820d17a` ?

**Comment by fredzzhang** [comment]
Hi @Dawn-LX,

The recommended way to clone the repo is listed in the [prerequisite](https://github.com/fredzzhang/upt#prerequisites) section. You shouldn't need to clone the submodules separately. The following lines should do the trick.

```bash
git clone https://github.com/fredzzhang/upt.git
cd upt
git submodule init
git submodule update
```

Fred.

**Comment by Dawn-LX** [comment]
> Hi @Dawn-LX,
> 
> The recommended way to clone the repo is listed in the [prerequisite](https://github.com/fredzzhang/upt#prerequisites) section. You shouldn't need to clone the submodules separately. The following lines should do the trick.
> 
> ```shell
> git clone https://github.com/fredzzhang/upt.git
> cd upt
> git submodule init
> git submodule update
> ```
> 
> Fred.

@fredzzhang  Thank you ! I get it !
That's how we use `.gitmodules` : )
