### ISSUE TITLE
UPT predicts scenario 1 of V-COCO

### ISSUE THREAD

**Issue by hutuo1213** [fredzzhang/upt#79]
Hi,

Based on your tips, I solved the above problem. 
I would like to know how the UPT predicts scenario 1 and scenario 2, which needs to be predicted as [0,0,0,0] for occlusion objects. Scenario 2 needs to ignore object prediction. Does UPT have the function to predict [0,0,0,0] of the occluded object?

Thank you so much!
yaoyaosanqi.

**Comment by fredzzhang** [comment]
Hi @yaoyaosanqi,

We didn't design special mechanism to handle occluded objects. Therefore, scenario 2 reflects the true performance of the model more, since the occluded triplets are ignored in the mAP calculation.

Fred.

**Comment by hutuo1213** [comment]
Cheers.
