### ISSUE TITLE
Real-time measurement

### ISSUE THREAD

**Issue by 131413ljk** [fredzzhang/upt#82]
HI，Thanks for your amazing work. I noticed that UPT is near real-time performance on a single GPU and reported 24FPS results in the article, I would like to know how this 24FPS is measured, it would be very helpful for me, thank you.

**Comment by fredzzhang** [comment]
Hi @131413ljk,

We used a RTX 3090 for the inference speed benchmark. To get the FPS, we recorded the time to run the model on the entire test set and took the average speed. To get this statistic, a simple way is to take the evaluation code and comment out everything after the forward pass.

Hope that helps.

Fred.
