### ISSUE TITLE
GFLOPs and params

### ISSUE THREAD

**Issue by hutuo1213** [fredzzhang/upt#83]
Hi, Dr. Zhang,
We found <Re-mine, Learn and Reason: Exploring the Cross-modal Semantic Correlations for Language-guided HOI detection> reports the following:
![image](https://github.com/fredzzhang/upt/assets/112799241/a5cf0e6c-049e-4e30-9bb7-30fb049071b3)
We are puzzled by the scoring of MACs (G): UPT contains DETR and interaction head, but MACs (G) are very close. What is causing this?

We compared the number of parameters and GFLOPs for QPIC and UPT. The image size is [3,887,1055] and the test results are as follows:

QPIC: Parameters: 41.462M GFLOPs: 91.82
UPT: Parameters: 54.763M (interaction head 13.241M) GFLOPs: 91.91
(test with GeForce GTX 1080)

This seems similar to the table, can you tell me what is causing this?

**Comment by fredzzhang** [comment]
Hi @yaoyaosanqi,

Good observation. The computational cost of UPT is indeed heavily centred on the first stage. The second stage, i.e., the interaction head, only processes a small number of tokens, be it unary or pairwise. Normally, you'd have about 10 detected humans and objects in each image after the filtering. That's a very small number of unary tokens. Similarly, the pairwise layer didn't need to process a lot of tokens, either.

On the other hand, the unary and pairwise layers are both self-attention layers, with higher dimensions than what was in DETR (256). So the parameter count does go up disproportionally.

Fred.
