### ISSUE TITLE
suppress overconfident objects

### ISSUE THREAD

**Issue by hutuo1213** [fredzzhang/upt#85]
Hi,

We found that "suppress overconfident objects" works on HICO-DET but hardly works on V-COCO.
Our work is in HICO-DET:
```python
resnet50: λ=1.0 32.10mAP λ=1.9 33.44mAP λ=2.8 33.63mAP
resnet101: λ=1.0 32.48mAP λ=1.9 33.63mAP λ=2.8 33.79mAP
```
UPT in V-COCO:
```python
resnet50: λ=1.0 58.9mAP λ=2.8 59.0mAP
resnet101: λ=1.0 60.7mAP λ=2.8 60.7mAP
```

Our existing view, this strategy works in HICO-DET and closes the gap between resnet50 and resnet101.
Is it possible to find a unified view to explain the phenomena on HICO-DET and V-COCO?

**Comment by fredzzhang** [comment]
Hi @hutuo1213,

Sorry for the late reply! The choice of $\lambda$ was determined on the HICO-DET dataset through a simple hyper-parameter search. I simply used the same value for V-COCO. So it's not really optimised for V-COCO.

The use of $\lambda$ is more of a trick, so I did not investigate too much into it.

Fred.
