### ISSUE TITLE
VCOCO evaluation

### ISSUE THREAD

**Issue by aqingcv** [fredzzhang/upt#86]
For V-COCO, you  use the utilities provided by [Gupta et al](https://github.com/s-gupta/v-coco#evaluation), but the length of the test dataset is 4532 in your code，this means that the resulting cache.pkl contains only 4532 outputs. However, in the utilities provided by [Gupta et al.](https://github.com/s-gupta/v-coco#evaluation),  the images in the v-coco/data/splits/vcoco_test.ids is 4946, which is not equal to the 4532. Will this affect the final test results? Thanks.

**Comment by fredzzhang** [comment]
Hi @aqingcv,

I vaguely remember that I removed those images without valid human-object interactions, since some annotations in V-COCO only have <subject, predicate> pairs, but not the triplets. 

Fred.
