### ISSUE TITLE
v-coco data

### ISSUE THREAD

**Issue by Maritime-Moon** [fredzzhang/upt#88]
Why is it that in the link you provided, I found that the COCO dataset has 82,783 images, while the dataset you are talking about seems to have only 10,346 images.

**Comment by fredzzhang** [comment]
Hi @Maritime-Moon,

The V-COCO dataset is a subset of the MS COCO dataset, with additional verb annotations. See more details in this [technical report](https://arxiv.org/abs/1505.04474).

Fred.
