### ISSUE TITLE
inference with fine-tuned DETR models

### ISSUE THREAD

**Issue by Cherryjingyao** [fredzzhang/upt#89]
how to run inference with fine-tuned DETR models
how to set the args ,the default is to use the downloaded detr weights

**Comment by fredzzhang** [comment]
Hi @Cherryjingyao,

The provided UPT weights already include the fine-tuned DETR weights. Even when the pre-trained DETR weights are specified in the arguments, they will be overridden once the UPT weights are loaded.

Fred.
